#!/bin/bash
VERSION="$1"
: "${VERSION:="latest"}"

REPO_RAW_URL="https://github.com/LamaAni/zbash_config"

if [ "$VERSION" != "latest" ]; then
  URL="$REPO_RAW_URL/releases/download/$VERSION"
else
  URL="$REPO_RAW_URL/releases/latest/download"
fi

URL="$URL/zbash_config.sh?v_$(date +"%S")=$RANDOM"
echo "[Downloading] $URL" 1>&2
SCRIPT="$(curl -sL "$URL")"
if [ -z "$SCRIPT" ]; then
  echo 1>&2 "Error when downloading script. Script empty or failed to download."
  exit 2
fi
if [ "$SCRIPT" == "Not Found" ]; then
  echo 1>&2 "Cloud not find script @ $URL"
  exit 2
fi
printf "%s" "$SCRIPT"
