#!/bin/bash
VERSION="$1"
: "${VERSION:="latest"}"

REPO_RAW_URL="https://github.com/LamaAni/zbash-config"

if [ "$VERSION" != "latest" ]; then
  URL="$REPO_RAW_URL/releases/download/$VERSION"
else
  URL="$REPO_RAW_URL/releases/latest/download"
fi

URL="$URL/zbash_config.sh?v_$(date +"%S")=$RANDOM"

SCRIPT="$(curl -sL "$URL")"
if [ "$SCRIPT" == "Not Found" ]; then
  echo 1>&2 "Cloud not find script @ $URL"
  exit 1
fi
printf "%s" "$SCRIPT"
