#!/usr/bin/env bash
cur_path="$(dirname ${BASH_SOURCE[0]})"
LOG_PREFEX=""

function log() {
  echo "$LOG_PREFEX$1"
}

function get_yes_no() {
  while true; do
    read -p "$LOG_PREFEX$1 [y/n]: " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[YyNn]$ ]]; then
      log "Input invalid: you must specify y or n."
    else
      break
    fi
  done

  export REPLY
}

function assert() {
  if [ $1 -ne 0 ]; then
    log "$2"
    return $1
  fi
}

: ${OSH:="$HOME/.oh-my-bash"}
: ${OSH_CUSTOM:="$OSH/custom"}

log "Looking for oh-my-bash @ $OSH"

# check for oh_my_bash
if [ ! -d "$OSH" ]; then
  log "The script requires the installation of oh_my_bash @ ~/.oh_my_bash, repo not found."
  get_yes_no "Would you like to install oh-my-bash now? (requires git, curl) [y/n] "
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    log "Aborted"
    exit 0
  fi

  log "Cloning remote repo.."
  log "Installing oh-my-bash.. (skipping bash terimal - will be executed later)"
  OH_MY_BASH_INSTALL=$(curl -fsSL "https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh")
  OH_MY_BASH_INSTALL=$(echo "$OH_MY_BASH_INSTALL" | sed -e "s/exec bash; source \\\$HOME\\/[.]bashrc//g")
  
  bash -c "$OH_MY_BASH_INSTALL"
fi

# Install script for bash configuration.
log "This package installs the zlib/bash-config. This script will alter the current configuration of oh_my_bash, and augment .bashrc"
get_yes_no "Are you sure?"

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
  log "Aborted"
  exit 0
fi

OSH_CUSTOM_THEMES="$OSH_CUSTOM/themes"
themes_src=$(realpath $cur_path/../themes)

log "Linking themes to $OSH_CUSTOM_THEMES"
for d in $themes_src/*/; do
  target_name="$OSH_CUSTOM_THEMES/$(basename $d)"
  log "Linking $d -> $target_name"
  ln -sf "$d" "$target_name"
done

OSH_CUSTOM_ALIASES="$OSH_CUSTOM/aliases"
aliases_src=$(realpath $cur_path/../aliases)
log "Linking aliases to $OSH_CUSTOM_ALIASES"
for f in $aliases_src/*; do
  target_name="$OSH_CUSTOM_ALIASES/$(basename $f)"
  log "Linking $f -> $target_name"
  ln -sf "$f" "$target_name"
done

log " -- Augmenting bashrc:"
node "$cur_path/format_bashrc.js"
assert $? "could not augment bashrc" || exit 1
log "Done."

VALIDATE_CHANGED=$(cat ~/.bashrc | grep "OSH_THEME")
if [ "$VALIDATE_CHANGED" == 'OSH_THEME="font"' ]; then
  assert 1 "ERROR: Failed to replace osh theme" || exit $?
fi

log "Entering a new bash termianl, settings updated."
if [ "$1" != '--skip-bash' ]; then
  exec bash; source $HOME/.bashrc
fi