name: "Compile scripts"

on:
  pull_request:
    branches:
      - "master"
  release:
    branches:
      - "master"
    types:
      - created
  push:
    branches:
      - master
jobs:
  compile_scripts:
    runs-on: ubuntu-latest
    steps:
      - name: "Cancel previous runs on same branch"
        uses: rokroskar/workflow-run-cleanup-action@v0.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: "Checkout the code"
        uses: actions/checkout@v2

      - name: "Compile the code"
        id: compile
        run: bash src/compile >| zbash_config.sh && chmod +x zbash_config.sh

      - name: "Test the code"
        id: test_code
        run: zbash_config.sh test

      - name: "Release: Upload files"
        if: github.event_name == 'release'
        uses: AButler/upload-release-assets@v2.0
        with:
          files: "zbash_config.sh"
          release-tag: "${{steps.args.outputs.version}}"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
